### PR TITLE
Testing Enumerables

### PR DESCRIPTION
**Pull request by pountzas**
- add my_each test cases
- add my_each_with_index test cases
- add my_select test cases
- add my_count test cases
- add my_map test cases
- add my_all test cases
- add my_any test cases
- add my_none test cases
- add my_inject test cases
- add multiply_els test cases

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
# 🔴  Changes Required 🔴  

Hello @pountzas, you did a great job with your rspecs, every single one works as expected🔥, just a few changes are required:

- [x]  Add a section in your README file about how to run your rspecs
- [ ] Check rubocop, you have 11 offenses locally.

You can contact me on slack if you have any questions just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!👨🏽‍💻  🖥️

**Comment by pountzas** [comment]
All offenses were fixed locally and didn't pass the test on GitHub, so I removed them. If you notice this is referred to on commits above.

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required

Hello @pountzas, thank you for implementing the requested changes by the previous reviewer.

## To Improve
- [ ] As requested by the previous reviewer, please understand that it is a necessary requirement for your code to pass the Rubocop guides.
> You can use magic comments to turn off only the necessary guides, note that it is advisable that you do not overuse them.

Happy coding, keep up the energy. 💪

> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

**Comment by pountzas** [comment]
Trying to change the parameters on rubocop.yml simply does not work.

rubocopYML

Changes made in order to pass Github Rubocop tests which are mandatory and most important than local errors.

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
# Status: Change Requested

Good job @pountzas is inspiring to see how hard you worked for this project but you still have to take one step and you are ready for the next project

- Rubocop still showing many errors you can do more research on how you can solve this and also you can go through your code to see how you can change some to meet the requirements

test

## I am sure you will do this try to fix that and submit for another code review

## Happy Coding image

best,

Lydia Ingabire

**Comment by DeliceLydia** [comment]
Hello! this PR must be approved as long as GitHub actions don't have errors we don't have to mind locally.

Thank you!

**Review by DeliceLydia — APPROVED** [review]
# Status: Approved image

Congratulations @pountzas for implementing all changes requested and finishing your project
keep working hard

## Feel free to merge and move on to the next project

All the best,

Lydia Ingabire

**Comment by cyonii** [comment]
Hello @pountzas 

I've just realized that I mentioned that you could edit rubocop's configurations - `rubocop.yml` - and that is completely a mistake on my side.
I am sorry to mislead you. I haven't done that on purpose :blush:

I hope you remember this in the future.

**Pull request merged**
